# Generated by Django 3.1.6 on 2021-02-04 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practices.course')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='QuestionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_type', models.CharField(choices=[('EN', 'English'), ('PY', 'Python Language'), ('JL', 'Java Language'), ('ME', 'Math Expression'), ('IN', 'Inputs to program'), ('OT', 'Output of program'), ('CO', 'Constraint or condition of output'), ('SP', 'Special patterns')], max_length=2)),
                ('text_area', models.TextField()),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='practices.question')),
            ],
            options={
                'verbose_name': 'PlainText',
                'verbose_name_plural': 'PlainTexts',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practices.topic'),
        ),
        migrations.CreateModel(
            name='AnswerText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_type', models.CharField(choices=[('EN', 'English'), ('PY', 'Python Language'), ('JL', 'Java Language'), ('ME', 'Math Expression'), ('IN', 'Inputs to program'), ('OT', 'Output of program'), ('CO', 'Constraint or condition of output'), ('SP', 'Special patterns')], max_length=2)),
                ('text_area', models.TextField()),
                ('answer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='practices.answer')),
            ],
            options={
                'verbose_name': 'PlainText',
                'verbose_name_plural': 'PlainTexts',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practices.question'),
        ),
    ]
